name: hotsos
adopt-info: hotsos
summary: Collect application operational information.
description: |
  Use hotsos to implement repeatable analysis and extract useful information
  from common cloud applications and subsystems. Write analysis Scenarios in
  YAML using a high-level language and helpful Python libraries. A catalog of
  analysis implementations is included.

  Hotsos is plugin-oriented, providing easy access to the state of
  applications and subsystems. Hotsos is run against a Data Root which can
  either be the host it is run on or a sosreport. Output is a summary of key
  information from each plugin along with issuses or known bugs detected and
  suggestions on what actions can be taken to handle them.

  Installation and Usage: https://hotsos.readthedocs.io/en/latest/install/index.html
  Contributing: https://hotsos.readthedocs.io/en/latest/contrib/index.html
  Full documentation: https://hotsos.readthedocs.io/en/latest/
confinement: strict
grade: stable
base: core22
plugs:
  shared-memory:
    private: true
environment:
  REPO_INFO_PATH: $SNAP/repo-info
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

# dpkg won't work without this
layout:
  /etc/dpkg/dpkg.cfg:
    bind-file: $SNAP_DATA/etc/dpkg/dpkg.cfg
  /etc/dpkg/dpkg.cfg.d:
    bind: $SNAP_DATA/etc/dpkg/dpkg.cfg.d

apps:
  hotsos:
    command: bin/hotsos
    completer: usr/share/hotsos/bash-completion/completions/hotsos-complete
    plugs:
      - home
      - network
      - network-bind
parts:
  hotsos:
    plugin: python
    source: .
    build-packages:
      - python3-pip
    stage-packages:
      - bsdmainutils
      - coreutils
      - dpkg
      - systemd
    python-requirements:
      - requirements.txt
    override-build: |
      set -e -u -x
      git rev-parse --short HEAD > hotsos/.repo-info
      pip install setuptools-git-versioning
      craftctl set version="$(setuptools-git-versioning)"
      craftctl default
    override-stage: |
      set -e -u -x
      install -D \
        ${CRAFT_PART_BUILD}/scripts/hotsos-complete \
        ${CRAFT_PART_INSTALL}/usr/share/hotsos/bash-completion/completions/hotsos-complete
      craftctl default
